repos:
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/pycqa/flake8
  rev: 7.2.0  # pick a git hash / tag to point to
  hooks:
  - id: flake8
    additional_dependencies:
      - flake8-qgis==1.1.0
    args: [--config=.flake8]
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
      name: isort (python)
      args: [--filter-files]
