# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qvalhalla/resources/ui/dlg_from_layer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FromLayerDialog(object):
    def setupUi(self, FromLayerDialog):
        FromLayerDialog.setObjectName("FromLayerDialog")
        FromLayerDialog.resize(400, 94)
        self.verticalLayout = QtWidgets.QVBoxLayout(FromLayerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.from_layer = gui.QgsMapLayerComboBox(FromLayerDialog)
        self.from_layer.setObjectName("from_layer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.from_layer)
        self.label = QtWidgets.QLabel(FromLayerDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(FromLayerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FromLayerDialog)
        self.buttonBox.accepted.connect(FromLayerDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(FromLayerDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FromLayerDialog)

    def retranslateUi(self, FromLayerDialog):
        _translate = QtCore.QCoreApplication.translate
        FromLayerDialog.setWindowTitle(_translate("FromLayerDialog", "Import From Layer"))
        self.label.setText(_translate("FromLayerDialog", "Layer"))
from qgis import gui
