# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qvalhalla/resources/ui/dlg_graph_from_pbf.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphFromPBF(object):
    def setupUi(self, GraphFromPBF):
        GraphFromPBF.setObjectName("GraphFromPBF")
        GraphFromPBF.resize(478, 189)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GraphFromPBF.sizePolicy().hasHeightForWidth())
        GraphFromPBF.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(GraphFromPBF)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(GraphFromPBF)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(GraphFromPBF)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(GraphFromPBF)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ui_text_name = QtWidgets.QLineEdit(GraphFromPBF)
        self.ui_text_name.setObjectName("ui_text_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ui_text_name)
        self.ui_pbf_file = QgsFileWidget(GraphFromPBF)
        self.ui_pbf_file.setObjectName("ui_pbf_file")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ui_pbf_file)
        self.ui_int_threads = QtWidgets.QSpinBox(GraphFromPBF)
        self.ui_int_threads.setObjectName("ui_int_threads")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ui_int_threads)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(GraphFromPBF)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GraphFromPBF)
        self.buttonBox.accepted.connect(GraphFromPBF.accept) # type: ignore
        self.buttonBox.rejected.connect(GraphFromPBF.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GraphFromPBF)

    def retranslateUi(self, GraphFromPBF):
        _translate = QtCore.QCoreApplication.translate
        GraphFromPBF.setWindowTitle(_translate("GraphFromPBF", "Build Graph From PBF"))
        self.label.setText(_translate("GraphFromPBF", "Name"))
        self.label_2.setText(_translate("GraphFromPBF", "PBF"))
        self.label_3.setText(_translate("GraphFromPBF", "Threads"))
        self.ui_int_threads.setToolTip(_translate("GraphFromPBF", "If 0, defaults to all available threads"))
from qgsfilewidget import QgsFileWidget
