# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qvalhalla/resources/ui/dlg_from_json.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FromValhallaJsonDialog(object):
    def setupUi(self, FromValhallaJsonDialog):
        FromValhallaJsonDialog.setObjectName("FromValhallaJsonDialog")
        FromValhallaJsonDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(FromValhallaJsonDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(FromValhallaJsonDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.json_field = QtWidgets.QTextEdit(FromValhallaJsonDialog)
        self.json_field.setObjectName("json_field")
        self.verticalLayout.addWidget(self.json_field)
        self.buttonBox = QtWidgets.QDialogButtonBox(FromValhallaJsonDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FromValhallaJsonDialog)
        self.buttonBox.accepted.connect(FromValhallaJsonDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(FromValhallaJsonDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FromValhallaJsonDialog)

    def retranslateUi(self, FromValhallaJsonDialog):
        _translate = QtCore.QCoreApplication.translate
        FromValhallaJsonDialog.setWindowTitle(_translate("FromValhallaJsonDialog", "From Valhalla JSON"))
        self.label.setText(_translate("FromValhallaJsonDialog", "Paste a valid Valhalla JSON array of locations:"))
        self.json_field.setPlaceholderText(_translate("FromValhallaJsonDialog", "e.g. [ { \"lon\": 13.4292, \"lat\": 52.515503 }, { \"lon\": 13.428969, \"lat\": 52.515526 }, { \"lon\": 13.428948, \"lat\": 52.515526 }, { \"lon\": 13.428936, \"lat\": 52.515638 }, { \"lon\": 13.428948, \"lat\": 52.515738 } ]"))
