# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valhalla/resources/ui/dlg_config_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigEditor(object):
    def setupUi(self, ConfigEditor):
        ConfigEditor.setObjectName("ConfigEditor")
        ConfigEditor.resize(607, 785)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ui_text = QtWidgets.QTextEdit(ConfigEditor)
        self.ui_text.setObjectName("ui_text")
        self.verticalLayout.addWidget(self.ui_text)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfigEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ConfigEditor)
        self.buttonBox.accepted.connect(ConfigEditor.accept) # type: ignore
        self.buttonBox.rejected.connect(ConfigEditor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConfigEditor)

    def retranslateUi(self, ConfigEditor):
        _translate = QtCore.QCoreApplication.translate
        ConfigEditor.setWindowTitle(_translate("ConfigEditor", "Valhalla Configuration"))
