# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valhalla/resources/ui/dlg_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(370, 203)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(0, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(AboutDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_3 = QtWidgets.QLabel(AboutDialog)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.label_2 = QtWidgets.QLabel(AboutDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ui_plugin_version_text = QtWidgets.QLabel(AboutDialog)
        self.ui_plugin_version_text.setTextFormat(QtCore.Qt.RichText)
        self.ui_plugin_version_text.setOpenExternalLinks(True)
        self.ui_plugin_version_text.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.ui_plugin_version_text.setObjectName("ui_plugin_version_text")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ui_plugin_version_text)
        self.label_4 = QtWidgets.QLabel(AboutDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ui_valhalla_version_text = QtWidgets.QLabel(AboutDialog)
        self.ui_valhalla_version_text.setTextFormat(QtCore.Qt.RichText)
        self.ui_valhalla_version_text.setOpenExternalLinks(True)
        self.ui_valhalla_version_text.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.ui_valhalla_version_text.setObjectName("ui_valhalla_version_text")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ui_valhalla_version_text)
        self.label_5 = QtWidgets.QLabel(AboutDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.ui_data_age_text = QtWidgets.QLabel(AboutDialog)
        self.ui_data_age_text.setTextFormat(QtCore.Qt.PlainText)
        self.ui_data_age_text.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.ui_data_age_text.setObjectName("ui_data_age_text")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ui_data_age_text)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AboutDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About Valhalla"))
        self.label.setText(_translate("AboutDialog", "Author"))
        self.label_3.setText(_translate("AboutDialog", "<html><head/><body><p><a href=\"https://github.com/nilsnolde\"><span style=\" text-decoration: underline; color:#0000ff;\">Nils Nolde</span></a></p></body></html>"))
        self.label_2.setText(_translate("AboutDialog", "Plugin version"))
        self.ui_plugin_version_text.setText(_translate("AboutDialog", "version text"))
        self.label_4.setText(_translate("AboutDialog", "Valhalla version"))
        self.ui_valhalla_version_text.setText(_translate("AboutDialog", "version text"))
        self.label_5.setText(_translate("AboutDialog", "Last graph update"))
        self.ui_data_age_text.setText(_translate("AboutDialog", "data age string"))
