# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valhalla/resources/ui/dlg_plugin_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PluginSettingsDialog(object):
    def setupUi(self, PluginSettingsDialog):
        PluginSettingsDialog.setObjectName("PluginSettingsDialog")
        PluginSettingsDialog.setWindowModality(QtCore.Qt.WindowModal)
        PluginSettingsDialog.resize(582, 525)
        PluginSettingsDialog.setWindowTitle("Valhalla - Settings")
        self.verticalLayout = QtWidgets.QVBoxLayout(PluginSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(PluginSettingsDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ui_binary_path = QgsFileWidget(PluginSettingsDialog)
        self.ui_binary_path.setStorageMode(QgsFileWidget.GetDirectory)
        self.ui_binary_path.setOptions(QtWidgets.QFileDialog.DontResolveSymlinks|QtWidgets.QFileDialog.ReadOnly|QtWidgets.QFileDialog.ShowDirsOnly)
        self.ui_binary_path.setObjectName("ui_binary_path")
        self.horizontalLayout.addWidget(self.ui_binary_path)
        self.ui_btn_default_binary_path = QtWidgets.QToolButton(PluginSettingsDialog)
        self.ui_btn_default_binary_path.setObjectName("ui_btn_default_binary_path")
        self.horizontalLayout.addWidget(self.ui_btn_default_binary_path)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.main_layout.addLayout(self.formLayout)
        self.ui_deps_group = QtWidgets.QGroupBox(PluginSettingsDialog)
        self.ui_deps_group.setObjectName("ui_deps_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ui_deps_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ui_deps_table = QtWidgets.QTableWidget(self.ui_deps_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_deps_table.sizePolicy().hasHeightForWidth())
        self.ui_deps_table.setSizePolicy(sizePolicy)
        self.ui_deps_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ui_deps_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ui_deps_table.setProperty("showDropIndicator", False)
        self.ui_deps_table.setDragDropOverwriteMode(False)
        self.ui_deps_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.ui_deps_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ui_deps_table.setShowGrid(False)
        self.ui_deps_table.setObjectName("ui_deps_table")
        self.ui_deps_table.setColumnCount(4)
        self.ui_deps_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ui_deps_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_deps_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_deps_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_deps_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.ui_deps_table)
        self.main_layout.addWidget(self.ui_deps_group)
        self.verticalLayout.addLayout(self.main_layout)

        self.retranslateUi(PluginSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(PluginSettingsDialog)

    def retranslateUi(self, PluginSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("PluginSettingsDialog", "Binaries"))
        self.ui_binary_path.setToolTip(_translate("PluginSettingsDialog", "Change the binary directory for Valhalla"))
        self.ui_btn_default_binary_path.setToolTip(_translate("PluginSettingsDialog", "Set the binary path to the pyvalhalla Python package (if installed)"))
        self.ui_btn_default_binary_path.setText(_translate("PluginSettingsDialog", "..."))
        self.ui_deps_group.setTitle(_translate("PluginSettingsDialog", "Dependencies"))
        item = self.ui_deps_table.horizontalHeaderItem(0)
        item.setText(_translate("PluginSettingsDialog", "Package"))
        item = self.ui_deps_table.horizontalHeaderItem(1)
        item.setText(_translate("PluginSettingsDialog", "Installed"))
        item = self.ui_deps_table.horizontalHeaderItem(2)
        item.setText(_translate("PluginSettingsDialog", "Available"))
from qgsfilewidget import QgsFileWidget
