# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valhalla/resources/ui/dlg_routing_dock.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoutingDialog(object):
    def setupUi(self, RoutingDialog):
        RoutingDialog.setObjectName("RoutingDialog")
        RoutingDialog.setWindowModality(QtCore.Qt.WindowModal)
        RoutingDialog.resize(720, 659)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RoutingDialog.sizePolicy().hasHeightForWidth())
        RoutingDialog.setSizePolicy(sizePolicy)
        RoutingDialog.setWindowTitle("Valhalla - Routing")
        self.verticalLayout = QtWidgets.QVBoxLayout(RoutingDialog)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(RoutingDialog)
        QtCore.QMetaObject.connectSlotsByName(RoutingDialog)

    def retranslateUi(self, RoutingDialog):
        pass
