# Form implementation generated from reading ui file 'valhalla/resources/ui/dlg_from_osrm_url.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FromOsrmUrlDialog(object):
    def setupUi(self, FromOsrmUrlDialog):
        FromOsrmUrlDialog.setObjectName("FromOsrmUrlDialog")
        FromOsrmUrlDialog.resize(400, 65)
        self.verticalLayout = QtWidgets.QVBoxLayout(FromOsrmUrlDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=FromOsrmUrlDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ui_url = QtWidgets.QLineEdit(parent=FromOsrmUrlDialog)
        self.ui_url.setObjectName("ui_url")
        self.horizontalLayout.addWidget(self.ui_url)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=FromOsrmUrlDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FromOsrmUrlDialog)
        self.buttonBox.accepted.connect(FromOsrmUrlDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(FromOsrmUrlDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FromOsrmUrlDialog)

    def retranslateUi(self, FromOsrmUrlDialog):
        _translate = QtCore.QCoreApplication.translate
        FromOsrmUrlDialog.setWindowTitle(_translate("FromOsrmUrlDialog", "From OSRM URL"))
        self.label.setText(_translate("FromOsrmUrlDialog", "OSRM URL"))
