# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valhalla/resources/ui/dlg_graph_from_url.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphFromUrl(object):
    def setupUi(self, GraphFromUrl):
        GraphFromUrl.setObjectName("GraphFromUrl")
        GraphFromUrl.resize(500, 229)
        self.formLayout = QtWidgets.QFormLayout(GraphFromUrl)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(GraphFromUrl)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ui_text_name = QtWidgets.QLineEdit(GraphFromUrl)
        self.ui_text_name.setObjectName("ui_text_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ui_text_name)
        self.label = QtWidgets.QLabel(GraphFromUrl)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ui_text_url = QtWidgets.QLineEdit(GraphFromUrl)
        self.ui_text_url.setObjectName("ui_text_url")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ui_text_url)
        self.label_2 = QtWidgets.QLabel(GraphFromUrl)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(GraphFromUrl)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)
        self.label_3 = QtWidgets.QLabel(GraphFromUrl)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ui_text_password = QgsPasswordLineEdit(GraphFromUrl)
        self.ui_text_password.setObjectName("ui_text_password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ui_text_password)
        self.ui_text_user = QtWidgets.QLineEdit(GraphFromUrl)
        self.ui_text_user.setObjectName("ui_text_user")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ui_text_user)

        self.retranslateUi(GraphFromUrl)
        self.buttonBox.accepted.connect(GraphFromUrl.accept) # type: ignore
        self.buttonBox.rejected.connect(GraphFromUrl.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GraphFromUrl)

    def retranslateUi(self, GraphFromUrl):
        _translate = QtCore.QCoreApplication.translate
        GraphFromUrl.setWindowTitle(_translate("GraphFromUrl", "Add Graph From URL"))
        self.label_4.setText(_translate("GraphFromUrl", "Name"))
        self.ui_text_name.setToolTip(_translate("GraphFromUrl", "Optional graph name (default: URL)"))
        self.ui_text_name.setPlaceholderText(_translate("GraphFromUrl", "optional, defaults to URL domain"))
        self.label.setText(_translate("GraphFromUrl", "URL"))
        self.ui_text_url.setToolTip(_translate("GraphFromUrl", "Graph URL (directory or tar file)"))
        self.label_2.setText(_translate("GraphFromUrl", "User"))
        self.label_3.setText(_translate("GraphFromUrl", "Password"))
        self.ui_text_password.setToolTip(_translate("GraphFromUrl", "Optional password for HTTP basic auth (will be stored in plain text in the settings)"))
        self.ui_text_password.setPlaceholderText(_translate("GraphFromUrl", "optional"))
        self.ui_text_user.setToolTip(_translate("GraphFromUrl", "Optional username for HTTP basic auth"))
        self.ui_text_user.setPlaceholderText(_translate("GraphFromUrl", "optional"))
from qgspasswordlineedit import QgsPasswordLineEdit
