# Form implementation generated from reading ui file 'valhalla/resources/ui/dlg_server_log.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ServerLog(object):
    def setupUi(self, ServerLog):
        ServerLog.setObjectName("ServerLog")
        ServerLog.resize(1029, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ServerLog.sizePolicy().hasHeightForWidth())
        ServerLog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ServerLog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_log = QtWidgets.QTextBrowser(parent=ServerLog)
        self.text_log.setMarkdown("")
        self.text_log.setObjectName("text_log")
        self.verticalLayout.addWidget(self.text_log)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ServerLog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ServerLog)
        self.buttonBox.accepted.connect(ServerLog.accept) # type: ignore
        self.buttonBox.rejected.connect(ServerLog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ServerLog)

    def retranslateUi(self, ServerLog):
        _translate = QtCore.QCoreApplication.translate
        ServerLog.setWindowTitle(_translate("ServerLog", "Valhalla Local Server Log"))
