# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valhalla/resources/ui/widget_graphs.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphWidget(object):
    def setupUi(self, GraphWidget):
        GraphWidget.setObjectName("GraphWidget")
        GraphWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(GraphWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ui_url_group = QtWidgets.QGroupBox(GraphWidget)
        self.ui_url_group.setObjectName("ui_url_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ui_url_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ui_btn_graph_add_tar = QtWidgets.QToolButton(self.ui_url_group)
        self.ui_btn_graph_add_tar.setObjectName("ui_btn_graph_add_tar")
        self.horizontalLayout_3.addWidget(self.ui_btn_graph_add_tar)
        self.ui_btn_graph_remove = QtWidgets.QToolButton(self.ui_url_group)
        self.ui_btn_graph_remove.setObjectName("ui_btn_graph_remove")
        self.horizontalLayout_3.addWidget(self.ui_btn_graph_remove)
        self.ui_btn_graph_folder = QtWidgets.QToolButton(self.ui_url_group)
        self.ui_btn_graph_folder.setObjectName("ui_btn_graph_folder")
        self.horizontalLayout_3.addWidget(self.ui_btn_graph_folder)
        self.ui_btn_settings = QtWidgets.QToolButton(self.ui_url_group)
        self.ui_btn_settings.setObjectName("ui_btn_settings")
        self.horizontalLayout_3.addWidget(self.ui_btn_settings)
        self.ui_btn_graph_log = QtWidgets.QToolButton(self.ui_url_group)
        self.ui_btn_graph_log.setObjectName("ui_btn_graph_log")
        self.horizontalLayout_3.addWidget(self.ui_btn_graph_log)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.ui_list_graphs = QtWidgets.QListView(self.ui_url_group)
        self.ui_list_graphs.setObjectName("ui_list_graphs")
        self.verticalLayout_3.addWidget(self.ui_list_graphs)
        self.verticalLayout.addWidget(self.ui_url_group)

        self.retranslateUi(GraphWidget)
        QtCore.QMetaObject.connectSlotsByName(GraphWidget)

    def retranslateUi(self, GraphWidget):
        _translate = QtCore.QCoreApplication.translate
        GraphWidget.setWindowTitle(_translate("GraphWidget", "Form"))
        self.ui_url_group.setTitle(_translate("GraphWidget", "Local Graphs"))
        self.ui_btn_graph_add_tar.setToolTip(_translate("GraphWidget", "Add an external graph to the library (will move the file)"))
        self.ui_btn_graph_add_tar.setText(_translate("GraphWidget", "..."))
        self.ui_btn_graph_remove.setToolTip(_translate("GraphWidget", "Remove a graph from the library"))
        self.ui_btn_graph_remove.setText(_translate("GraphWidget", "..."))
        self.ui_btn_graph_folder.setToolTip(_translate("GraphWidget", "set the graph library directory"))
        self.ui_btn_graph_folder.setText(_translate("GraphWidget", "..."))
        self.ui_btn_settings.setText(_translate("GraphWidget", "..."))
        self.ui_btn_graph_log.setText(_translate("GraphWidget", "..."))
