name: Test plugin - QGIS master

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.sh'
      - '**/metadata.txt'
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  PLUGIN_PATH: qvalhalla

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run linters & tests
        run: |
          docker pull qgis/qgis:latest
          docker run -dt --name qgis-testing-environment --network host -v "${GITHUB_WORKSPACE}":/tests_directory -e QT_QPA_PLATFORM="offscreen" qgis/qgis:latest
          # first run the docker/external valhalla_service tests; also allow verbose status
          docker run -dt --name valhalla-router -p 8002:8002 -v $PWD/tests/data:/custom_files -e tileset_name=andorra-tiles ghcr.io/valhalla/valhalla-scripted:latest
          sudo apt-get update && sudo apt-get install -y moreutils
          jq '.service_limits.status.allow_verbose = true' $PWD/tests/data/valhalla.json | sponge $PWD/tests/data/valhalla.json
          docker restart valhalla-router
          docker exec qgis-testing-environment bash -c "/tests_directory/tests/scripts/qgis_test_setup.sh latest ${{ env.PLUGIN_PATH }} tests/test_localhost_docker"
          # then with the plugin enabled and no external valhalla_service
          docker stop valhalla-router
          docker exec qgis-testing-environment bash -c "python3 -m pip install --break-system-packages pyvalhalla-weekly"
          docker exec qgis-testing-environment bash -c "/tests_directory/tests/scripts/qgis_test_setup.sh latest ${{ env.PLUGIN_PATH }} tests/test_localhost_plugin"


