name: Build OSX, Win & Python bindings

# this workflow:
# - runs master & PR pushes for OSX & Win
# - publishes Python bindings for all platforms and minor Python versions to:
#   - https://pypi.org/project/pyvalhalla/ for tag pushes
#   - https://pypi.org/project/pyvalhalla-git/ for master pushes

on:
  push:
    tags:
      - '*'

jobs:
  test:
    name: test tag stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Determine package to publish
        run: |
          VALHALLA_RELEASE_PKG="pyvalhalla"
          if [[ ${{ startsWith(github.ref, 'refs/tags*') }} == "true" ]]; then
            VALHALLA_RELEASE_PKG="${VALHALLA_RELEASE_PKG}-git"
          fi
          echo "github ref is ${{ github.ref }}
          echo "startswith result is ${{ startsWith(github.ref, 'refs/tags*') }}"
          echo "setting VALHALLA_RELEASE_PKG=${VALHALLA_RELEASE_PKG}"
          echo "VALHALLA_RELEASE_PKG=${VALHALLA_RELEASE_PKG}" >> $GITHUB_ENV
