on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Deploy plugin
        run: 
        run: |
          pip3 install qgis-plugin-ci
          qgis-plugin-ci \
          release ${GITHUB_REF/refs\/tags\//} \
          --github-token ${{ secrets.GITHUB_TOKEN }} \
          --osgeo-username nilsnolde \
          --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
