name: Build OSX, Win & Python bindings

# this workflow:
# - runs master & PR pushes for OSX & Win
# - publishes Python bindings for all platforms and minor Python versions to:
#   - https://pypi.org/project/pyvalhalla/ for tag pushes
#   - https://pypi.org/project/pyvalhalla-git/ for master pushes

on:
  push:
    tags:
      - '*'
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

env:
  # only run tmate if manually invoked and debug_enabled == true or a previous step failed
  SETUP_TMATE: ${{ ((github.event_name == 'workflow_dispatch') && (github.event.inputs.debug_enabled == 'true')) }}
  # only publish to PyPI on tags, schedule or workflow_dispatch (only on master!)
  PUBLISH_PYPI: ${{ (startsWith(github.ref, 'refs/tags') || (github.event_name == 'schedule') || ((github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/master'))) && (github.repository_owner == 'nilsnolde') }}

jobs:
  test:
    name: test tag stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: exit
        run: |
          echo "${{ env.SETUP_TMATE }}"
          exit 1

      - name: Determine package to publish
        if: ${{ env.SETUP_TMATE == 'true' || failure() }}
        run: |
          echo "${{ env.SETUP_TMATE }}"
          echo "${{ job.status == 'success' }}"
          echo "${{ job.status }}"
          echo "${{ github.repository_owner }}"
          echo "${{ github.repository_owner == 'nilsnolde' }}"
          echo "${{ (env.SETUP_TMATE == 'true') || (job.status == 'failure' && (github.repository_owner == 'nilsnolde')) }}"
